### ISSUE TITLE
Installation on MDPI server

### ISSUE THREAD

**Issue by targos** [cheminfo/molbank#8]
@mdpi-symfony

Have you tried to install the project on your server?
The documentation can be found in the readme: https://github.com/cheminfo/molbank#molbank

**Comment by ghost** [comment]
No, we would need a documentation for it.

**Comment by targos** [comment]
As I said, the procedure is documented here: https://github.com/cheminfo/molbank#molbank

Don't hesitate to ask if something is not clear enough.

**Comment by ghost** [comment]
Thank you, we will do it next week and keep you informed

**Comment by ghost** [comment]
Finally had some time to move forward with this. From the documentation, I can see we can install it locally in order to generate the output from our XML files, however, how to include it into our Molbank website? The idea would be to add the Molbank search into mdpi.com

**Comment by mdpi-symfony** [comment]
Tested the command and we're getting this exception:

sshadmin@mdpi-mem:/var/www/molbank$ sudo node generate --directory=/home/sshadmin/molbank-2018-M979.xml

/var/www/molbank/generate.js:3
process.on('unhandledRejection', (e) => {
                                      ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by mdpi-symfony** [comment]
After upgrading the Node.js to v8.9.4, the error is ass follows:

sshadmin@mdpi-mem:/var/www/molbank$ sudo node generate --directory=/home/sshadmin/molbank-2018-M979.xml
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOTDIR: not a directory, scandir '/home/sshadmin/molbank-2018-M979.xml'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.<anonymous> (/var/www/molbank/generate.js:27:21)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by ghost** [comment]
Worked now after upgrading to nodejs 8.x.x

Here is the output: 

sshadmin@mdpi-mem:/var/www/molbank$ sudo node generate --directory=/home/sshadmin --out=/tmp
treating 1 XML files
Missing mol2d: molbank-2018-M979
generated molbank-data.json and molbank-data.sdf in /tmp

What about the missing mol2d? The generated files seem empty.

Once we have the files generated, what to do with them?

**Comment by ghost** [comment]
Hi, any feedback on the previous question?

**Comment by targos** [comment]
"Missing mol2d" means that we were not able to find a ".mol" file in the supplementary material section of the XML.
We ignore such entries and print a warning because the molfile is required for the web application. This is why the generated files are empty.

**Comment by ghost** [comment]
Could you please explain it a bit better on the uploaded XML example, what is exactly needed for the tool to operate. Is there any kind of requirements?

[molbank-2018-M986.xml.zip](https://github.com/cheminfo/molbank/files/1819638/molbank-2018-M986.xml.zip)

**Comment by ghost** [comment]
Any news on this @targos ?
